import {
  ADDUSERREPOSITORY_TYPE,
  CHECKUSERBYEMAILREPOSITORY_TYPE,
  HASHER_TYPE,
  CHECKPASSWORD_TYPE,
  FINDUSERBYEMAILREPOSITORY_TYPE,
  ENCRYPTER_TYPE,
  DECRYPTER_TYPE,
} from "../data";
import { ADDUSER_TYPE, LOGIN_TYPE } from "../domain/usecases";

export const TYPES = {
  AddUser: ADDUSER_TYPE,
  AddUserRepository: ADDUSERREPOSITORY_TYPE,
  CheckUserByEmailRepository: CHECKUSERBYEMAILREPOSITORY_TYPE,
  Hasher: HASHER_TYPE,
  CheckPassowrd: CHECKPASSWORD_TYPE,
  FindUserByEmailRepository: FINDUSERBYEMAILREPOSITORY_TYPE,
  Login: LOGIN_TYPE,
  Encrypter: ENCRYPTER_TYPE,
  Decrypter: DECRYPTER_TYPE,
};
